#!/bin/bash

sudo true
git clone https://aur.archlinux.org/yay.git && cd yay/ && makepkg -si --noconfirm && cd .. && rm -rf yay/
yay -Sy --needed --noconfirm $(cat bin/base | egrep -v "^\s*(#|$)")
yay -Sy --needed --noconfirm $(cat bin/pkg | egrep -v "^\s*(#|$)")

sh install/app
sh install/zsh
sh install/configfile
sh install/neovim
