#!/bin/bash

sudo true
git clone https://aur.archlinux.org/yay.git && cd yay/ && makepkg -si --noconfirm && cd .. && rm -rf yay/
yay -Sy --needed --noconfirm $(cat bin/base | egrep -v "^\s*(#|$)")
yay -Sy --needed --noconfirm $(cat bin/pkg | egrep -v "^\s*(#|$)")

sh install/xdm
sh install/configs
sh install/neovim
sh install/zsh

#End
yay -Yc --noconfirm